CREATE DATABASE LAB2;

CREATE TABLE COUNTRIES (
  COUNTRY_ID SERIAL PRIMARY KEY,
  COUNTRY_NAME VARCHAR(12),
  REGION_ID INTEGER,
  POPULATION INTEGER
);

INSERT INTO COUNTRIES VALUES (1,'CHINA',7,20000000);

SELECT *FROM COUNTRIES;

INSERT INTO COUNTRIES(COUNTRY_ID, COUNTRY_NAME) VALUES (2, 'IRAN');

UPDATE COUNTRIES SET REGION_ID=NULL;
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME, REGION_ID, POPULATION)
VALUES (13, 'RUSSIA',55, 2230000),
       (29, 'UZBEKISTAN',66, 2800000),
       (86, 'KYRGYSTAN', 23,1200000);

ALTER TABLE COUNTRIES
    ALTER COLUMN COUNTRY_NAME SET DEFAULT 'KAZAKHSTAN';

INSERT INTO COUNTRIES VALUES (28, DEFAULT, 48, 980000);

INSERT INTO COUNTRIES (country_id, COUNTRY_NAME) VALUES (DEFAULT ,DEFAULT );

CREATE TABLE COUNTRIES_NEW(
  LIKE COUNTRIES
);
INSERT INTO COUNTRIES_NEW
SELECT *FROM COUNTRIES;
SELECT *FROM COUNTRIES_NEW;

UPDATE COUNTRIES_NEW SET REGION_ID = 1  WHERE REGION_ID IS NULL;

UPDATE COUNTRIES_NEW SET POPULATION = POPULATION + (POPULATION*0.1)
RETURNING COUNTRY_NAME, POPULATION AS "NEW POPULATION";

DELETE FROM COUNTRIES WHERE POPULATION<100000;

DELETE FROM COUNTRIES_NEW
AS IDEA USING COUNTRIES AS SQ
WHERE IDEA.COUNTRY_ID=SQ.COUNTRY_ID
RETURNING*;

DELETE FROM COUNTRIES
RETURNING *;
